#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    chmod 600 /etc/config/hbasstunet 2>/dev/null || true
    config_load hbasstunet
    config_get_bool enabled main enabled 0
    [ "$enabled" -eq 1 ] || return 0
    procd_open_instance
    procd_set_param command /usr/sbin/hbasstunet
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}
